version: '3'

services:
  shop_back:
    image: webdevops/php-dev:7.4-alpine
    ports:
     - "9003:9003"
    environment:
      - PHP_DEBUGGER=xdebug
      - XDEBUG_MODE=debug
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_CLIENT_PORT=9003
      - XDEBUG_IDE_KEY=PHP_IDE_CONFIG
